version: "3.9"

name: doc-share

volumes:
  s3-storage:
    driver: local
  db-data:
    driver: local
networks:
  app-network:
    driver: bridge
services:
  # infrastructure
  app-db:
    image: postgres:15-alpine
    container_name: app-postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - app-network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql.conf:ro
  file-storage:
    image: minio/minio:latest
    container_name: file-storage
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_PRIVATE_KEY}
    command: server ~/minio --console-address :9090
    ports:
      - ${MINIO_PORT}:9000
      - ${MINIO_UI_PORT}:9090
    networks:
      app-network:
    volumes:
      - s3-storage:/data