spring:
  config:
    import: optional:file:.env.local[.properties]
  application:
    name: doc-share
  liquibase:
    enabled: true
    default-schema: ${POSTGRES_SCHEMA}
    change-log: classpath:db/db.changelog.yml
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?currentSchema${POSTGRES_SCHEMA}
  r2dbc:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: r2dbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?currentSchema${POSTGRES_SCHEMA}&useUnicode=true&characterEncoding=UTF-8
    pool:
      enabled: true
      initial-size: 10
      max-idle-time: 1m
      max-size: 10
    name: ${POSTGRES_DB}
  data:
    r2dbc:
      repositories:
        enabled: true
  jpa:
    show-sql: true
logging:
  level:
    org.springframework.web.servlet.handler.HandlerMappingIntrospector: error

minio:
  bucket: ${MINIO_BUCKET}
  url: ${MINIO_HOST}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}

